export const ACTIONS = {
  NOTIFY: "NOTIFY",
  AUTH: "AUTH",
  GET_ALL_USERS: "GET_ALL_USERS",
  ADD_CART: "ADD_CART",
  ADD_MODAL: "ADD_MODAL",
  ADD_ORDERS: "ADD_ORDERS",
  ADD_CATEGORIES: "ADD_CATEGORIES",
};
