export const ACTIONS = {
  NOTIFY: "NOTIFY",
  AUTH: "AUTH",
  GET_ALL_USERS: "GET_ALL_USERS",
  ADD_CART: "ADD_CART",
  ADD_MODAL: "ADD_MODAL",
  ADD_ORDERS: "ADD_ORDERS",
  ADD_CATEGORIES: "ADD_CATEGORIES",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  ADD_BRANDS: "ADD_BRANDS",
  ALL_CONTACT_US: "ALL_CONTACT_US",
};
