import connectDB from "utils/connectDB";
const CC = require("currency-converter-lt");
connectDB();

export default async (req, res) => {
  switch (req.method) {
    case "GET":
      await usdAmount(req, res);
      break;
  }
};

// * Currency Convertor
const usdAmount = async (req, res) => {
  try {
    const { amount } = req.query;
    let currencyConverter = new CC();
    await currencyConverter
      .from("INR")
      .to("USD")
      .amount(parseInt(amount))
      .convert()
      .then((response) => res.json({ amount: response }));
  } catch (err) {
    // * Alternate way to convert INR to USD as if error generated BY currency-converter-lt
    console.log(err);
    const { amount } = req.query;
    const usdAmount = amount * 0.014;
    return res.json({ amount: usdAmount });
  }
};
